### ISSUE TITLE
How to add cloth-config to common module?

### ISSUE THREAD

**Issue by AdamCalculator** [jaredlll08/MultiLoader-Template#57]
![image](https://github.com/jaredlll08/MultiLoader-Template/assets/156993728/a7e6b783-debd-47dc-9b7a-49b43e101658)

**Comment by jaredlll08** [comment]
Since cloth uses Architectury, which is based on Loom, their common module is published using Intermediary mappings, not Mojmaps which VanillaGradle uses, so you cannot use their common module.

You can try to use the Forge module in Common, as those should both be mojmaps (in newer versions), however if that still doesn't work, then the answer is you don't (unless you write your own remapper that remaps the dep locally)

**Comment by AdamCalculator** [comment]
:sob:

**Comment by AdamCalculator** [comment]
@jaredlll08 Is there any configuration library that would work in such conditions?

**Comment by jaredlll08** [comment]
None that I know of.

A lot of people roll their own just using Gson.

**Comment by AdamCalculator** [comment]
![image](https://github.com/jaredlll08/MultiLoader-Template/assets/156993728/246f7bb5-1b26-4a98-a113-b2293492cbd3)
Perhaps I succeeded...
