### ISSUE TITLE
compatibilityLevel in mixins files

### ISSUE THREAD

**Issue by MrAmericanMike** [jaredlll08/MultiLoader-Template#72]
So I'm not really familiar with the whole `mixins` ecosystem, but I see that the mixins files in `common` and `forge` have `compatibilityLevel` set to `JAVA_18` and the ones in `fabric` and `neoforge` are set to `JAVA_21`

Is this intended?

(Minecraft 1.21)

**Comment by jaredlll08** [comment]
Both NeoForge and Fabric use Fabric's fork of mixin, however forge is still using the upstream Sponge Mixin, they have a [PR](https://github.com/MinecraftForge/MinecraftForge/pull/9958) to swap to Fabric's fork, however it doesn't seem like they are in a rush to merge it. 

That linked PR has information on the differences between the forks.

The reason that `common` needs the old compat level, is because the common mixin file is included in the forge jar, and forge will complain about it at runtime.
